name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3.0.2
        with:
          version: "1.12"

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v3

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
